sudo: required
services:
  # automatically install a docker instance
  - docker

before_install:
  - docker build -t uladzimirkalesny/react-docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true uladzimirkalesny/react-docker-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: react-docker-ci
  env: React-docker-ci-env
  bucket_name: elasticbeanstalk-us-east-1-996990238007
  bucket_path: react-docker-ci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY